version: '2'
services:
  pulsar:
    restart: always
    container_name: pulsar
    ports:
     - "8989:8080"
     - "6650:6650"
    command: 
      bin/pulsar standalone
    image: "apachepulsar/pulsar:2.11.0"
