services:
  spring-cloud-config-server:
    restart: always
    container_name: spring-cloud-config-server
    ports:
     - "8888:8888"
    volumes:
     - ./data:/data
    image: "hyness/spring-cloud-config-server"
    environment:
     - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/rramos/config-server.git
