---
services:
  spring-cloud-config-server:
    ports:
      - 8888:8888
    volumes:
      - ./data:/data
    image: hyness/spring-cloud-config-server
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=${CONFIG_SERVER_URI}
