version: "2"

networks:
  default:
    external:
      name: dockers

services:
  jenkins:
    container_name: jenkins
    ports:
      - 9090:8080
      - 50000:50000
    volumes:
      - ./data:/opt/data
      - ./jenkins_home:/var/jenkins_home
    image: jenkins/jenkins
