version: '2'
services:
  portainer:
    restart: always
    container_name: trino
    ports:
     - "7676:8080"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    image: "trinodb/trino"
