services:
  bigquery-emulator:
    ports:
     - "9050:9050"
    volumes:
     - ./data:/data
    image: "ghcr.io/goccy/bigquery-emulator:latest"
    container_name: bigquery-emulator
    command: "bigquery-emulator --project=test"

